---
# Usage: http://ruhoh.com/usage/configure/ 

RuhohSpec: '1.0'
theme : elton
production_url : http://blog.prosight.me

posts:
  permalink: /:categories/:title/
  summary_lines: 20
  latest: 10

pages:
  permalink: 'pretty'